# Generated by Django 5.2.15 on 2026-06-11 04:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppBusinessAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('waba_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('disabled', 'Disabled')], default='active', max_length=32)),
            ],
            options={
                'db_table': 'whatsapp_business_account',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='whatsapp_bu_organiz_7e97e4_idx'), models.Index(fields=['created_at'], name='whatsapp_bu_created_d70e6e_idx'), models.Index(fields=['organization_id', 'status'], name='whatsapp_bu_organiz_b29e8a_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization_id', 'waba_id'), name='uniq_whatsapp_business_account_org_waba', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppPhoneNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('phone_number_id', models.CharField(max_length=64)),
                ('display_phone_number', models.CharField(blank=True, max_length=64)),
                ('verified_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disconnected', 'Disconnected'), ('disabled', 'Disabled')], default='active', max_length=32)),
                ('business_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phone_numbers', to='whatsapp.whatsappbusinessaccount')),
            ],
            options={
                'db_table': 'whatsapp_phone_number',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppOutboundMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('sticker', 'Sticker'), ('location', 'Location'), ('contact_card', 'Contact card'), ('template', 'Template'), ('unsupported', 'Unsupported')], default='text', max_length=32)),
                ('body', models.TextField(blank=True)),
                ('template_name', models.CharField(blank=True, max_length=255)),
                ('external_message_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=32)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=255)),
                ('recipient_phone_e164', models.CharField(max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('queued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_outbound_messages', to='contacts.contact')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_outbound_messages', to='conversations.conversation')),
                ('crm_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_outbound_messages', to='conversations.message')),
                ('phone_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbound_messages', to='whatsapp.whatsappphonenumber')),
            ],
            options={
                'db_table': 'whatsapp_outbound_message',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppInboundMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('from_phone_e164', models.CharField(blank=True, max_length=20)),
                ('wa_id', models.CharField(blank=True, max_length=64)),
                ('external_message_id', models.CharField(max_length=255)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('sticker', 'Sticker'), ('location', 'Location'), ('contact_card', 'Contact card'), ('template', 'Template'), ('unsupported', 'Unsupported')], default='unsupported', max_length=32)),
                ('body', models.TextField(blank=True)),
                ('raw_message', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='received', max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_inbound_messages', to='contacts.contact')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_inbound_messages', to='conversations.conversation')),
                ('crm_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_inbound_messages', to='conversations.message')),
                ('phone_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_messages', to='whatsapp.whatsappphonenumber')),
            ],
            options={
                'db_table': 'whatsapp_inbound_message',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=32)),
                ('category', models.CharField(choices=[('utility', 'Utility'), ('marketing', 'Marketing'), ('authentication', 'Authentication'), ('internal_reminder', 'Internal reminder'), ('follow_up', 'Follow-up')], default='utility', max_length=32)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('paused', 'Paused'), ('disabled', 'Disabled'), ('draft', 'Draft')], default='draft', max_length=32)),
                ('components', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'whatsapp_template',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='whatsapp_te_organiz_842af7_idx'), models.Index(fields=['created_at'], name='whatsapp_te_created_c715ac_idx'), models.Index(fields=['organization_id', 'status'], name='whatsapp_te_organiz_517599_idx'), models.Index(fields=['organization_id', 'category'], name='whatsapp_te_organiz_ea2cf6_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization_id', 'name', 'language'), name='uniq_whatsapp_template_org_name_language', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('event_id', models.CharField(max_length=128)),
                ('event_type', models.CharField(choices=[('messages', 'Messages'), ('statuses', 'Statuses'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('raw_payload', models.JSONField(default=dict)),
                ('signature', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored'), ('duplicate', 'Duplicate')], default='received', max_length=32)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'whatsapp_webhook_event',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='whatsapp_we_organiz_8ce928_idx'), models.Index(fields=['created_at'], name='whatsapp_we_created_82e0ca_idx'), models.Index(fields=['organization_id', 'status', 'received_at'], name='whatsapp_we_organiz_5964f5_idx'), models.Index(fields=['organization_id', 'event_type'], name='whatsapp_we_organiz_2c9827_idx'), models.Index(fields=['event_id'], name='whatsapp_we_event_i_f5d95b_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization_id', 'event_id'), name='uniq_whatsapp_webhook_event_org_event', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessageStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('external_message_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('deleted', 'Deleted'), ('warning', 'Warning'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('status_timestamp', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('raw_status', models.JSONField(blank=True, default=dict)),
                ('outbound_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_statuses', to='whatsapp.whatsappoutboundmessage')),
                ('webhook_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='message_statuses', to='whatsapp.whatsappwebhookevent')),
            ],
            options={
                'db_table': 'whatsapp_message_status',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMediaReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('external_media_id', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('sticker', 'Sticker'), ('location', 'Location'), ('contact_card', 'Contact card'), ('template', 'Template'), ('unsupported', 'Unsupported')], default='unsupported', max_length=32)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('sha256', models.CharField(blank=True, max_length=128)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('queued', 'Queued'), ('downloading', 'Downloading'), ('downloaded', 'Downloaded'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='received', max_length=32)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('crm_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_media_references', to='conversations.messageattachment')),
                ('crm_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_media_references', to='conversations.message')),
                ('inbound_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='media_references', to='whatsapp.whatsappinboundmessage')),
                ('webhook_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='media_references', to='whatsapp.whatsappwebhookevent')),
            ],
            options={
                'db_table': 'whatsapp_media_reference',
            },
        ),
        migrations.AddField(
            model_name='whatsappinboundmessage',
            name='webhook_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_messages', to='whatsapp.whatsappwebhookevent'),
        ),
        migrations.AddIndex(
            model_name='whatsappphonenumber',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='whatsapp_ph_organiz_f4e54c_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappphonenumber',
            index=models.Index(fields=['created_at'], name='whatsapp_ph_created_6d2e50_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappphonenumber',
            index=models.Index(fields=['organization_id', 'status'], name='whatsapp_ph_organiz_e13b0b_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappphonenumber',
            index=models.Index(fields=['phone_number_id'], name='whatsapp_ph_phone_n_d46a2f_idx'),
        ),
        migrations.AddConstraint(
            model_name='whatsappphonenumber',
            constraint=models.UniqueConstraint(fields=('organization_id', 'phone_number_id'), name='uniq_whatsapp_phone_number_org_external', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='whatsappoutboundmessage',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='whatsapp_ou_organiz_e71517_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappoutboundmessage',
            index=models.Index(fields=['created_at'], name='whatsapp_ou_created_19d331_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappoutboundmessage',
            index=models.Index(fields=['organization_id', 'external_message_id'], name='whatsapp_ou_organiz_4300db_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappoutboundmessage',
            index=models.Index(fields=['organization_id', 'status', 'created_at'], name='whatsapp_ou_organiz_194e64_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappoutboundmessage',
            index=models.Index(fields=['organization_id', 'conversation', 'created_at'], name='whatsapp_ou_organiz_d9e8e1_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappoutboundmessage',
            index=models.Index(fields=['organization_id', 'contact', 'created_at'], name='whatsapp_ou_organiz_376dbe_idx'),
        ),
        migrations.AddConstraint(
            model_name='whatsappoutboundmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('organization_id', 'idempotency_key'), name='uniq_whatsapp_outbound_org_idempotency_key'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagestatus',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='whatsapp_me_organiz_355ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagestatus',
            index=models.Index(fields=['created_at'], name='whatsapp_me_created_e27018_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagestatus',
            index=models.Index(fields=['organization_id', 'external_message_id'], name='whatsapp_me_organiz_a5f387_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagestatus',
            index=models.Index(fields=['outbound_message', 'created_at'], name='whatsapp_me_outboun_12bc90_idx'),
        ),
        migrations.AddConstraint(
            model_name='whatsappmessagestatus',
            constraint=models.UniqueConstraint(fields=('organization_id', 'external_message_id', 'status', 'status_timestamp'), name='uniq_whatsapp_message_status_org_external_status_ts', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='whatsappmediareference',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='whatsapp_me_organiz_74da66_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmediareference',
            index=models.Index(fields=['created_at'], name='whatsapp_me_created_f902b0_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmediareference',
            index=models.Index(fields=['organization_id', 'status', 'created_at'], name='whatsapp_me_organiz_7ad0ad_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmediareference',
            index=models.Index(fields=['organization_id', 'external_media_id'], name='whatsapp_me_organiz_c43f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmediareference',
            index=models.Index(fields=['inbound_message'], name='whatsapp_me_inbound_303f7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='whatsappmediareference',
            constraint=models.UniqueConstraint(fields=('organization_id', 'external_media_id'), name='uniq_whatsapp_media_reference_org_external_media', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='whatsappinboundmessage',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='whatsapp_in_organiz_c20e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappinboundmessage',
            index=models.Index(fields=['created_at'], name='whatsapp_in_created_6b8845_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappinboundmessage',
            index=models.Index(fields=['organization_id', 'conversation', 'received_at'], name='whatsapp_in_organiz_7e9207_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappinboundmessage',
            index=models.Index(fields=['organization_id', 'contact', 'received_at'], name='whatsapp_in_organiz_0006ad_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappinboundmessage',
            index=models.Index(fields=['organization_id', 'external_message_id'], name='whatsapp_in_organiz_0fd3a6_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappinboundmessage',
            index=models.Index(fields=['webhook_event'], name='whatsapp_in_webhook_6a534c_idx'),
        ),
        migrations.AddConstraint(
            model_name='whatsappinboundmessage',
            constraint=models.UniqueConstraint(fields=('organization_id', 'external_message_id'), name='uniq_whatsapp_inbound_org_external_message', nulls_distinct=False),
        ),
    ]
