# Generated by Django 5.2.15 on 2026-06-16 17:35

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('contact_phone', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('dead_letter', 'Dead letter')], default='pending', max_length=32)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_reason', models.TextField(blank=True)),
                ('prospect_id', models.UUIDField(blank=True, null=True)),
                ('conversation_id', models.UUIDField(blank=True, null=True)),
                ('contact_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'whatsapp_outbound_message_queue',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='whatsapp_ou_organiz_51744f_idx'), models.Index(fields=['created_at'], name='whatsapp_ou_created_72b3be_idx'), models.Index(fields=['organization_id', 'status', 'available_at'], name='whatsapp_ou_organiz_c6b2be_idx'), models.Index(fields=['organization_id', 'conversation_id'], name='whatsapp_ou_organiz_bf1b1a_idx'), models.Index(fields=['organization_id', 'contact_id'], name='whatsapp_ou_organiz_dd1d62_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization_id', 'idempotency_key'), name='uniq_bridge_outbound_org_idempotency', nulls_distinct=False)],
            },
        ),
    ]
