# Generated by Django 5.2.15 on 2026-06-12 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('type', models.CharField(choices=[('hot_lead', 'Hot lead'), ('call_requested', 'Call requested'), ('urgent_ticket', 'Urgent ticket'), ('task_due', 'Task due'), ('task_overdue', 'Task overdue'), ('ai_failure', 'AI failure'), ('whatsapp_failure', 'WhatsApp failure'), ('system_alert', 'System alert'), ('daily_digest', 'Daily digest')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('archived', 'Archived'), ('cancelled', 'Cancelled')], default='unread', max_length=16)),
                ('resource_type', models.CharField(blank=True, max_length=64)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('deduplication_key', models.CharField(blank=True, max_length=255)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
            },
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('dashboard', 'Dashboard'), ('email', 'Email'), ('system', 'System')], max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=16)),
                ('is_default', models.BooleanField(default=False)),
                ('configuration', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'notifications_channel',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='notificatio_organiz_3941bd_idx'), models.Index(fields=['created_at'], name='notificatio_created_179f74_idx'), models.Index(fields=['organization_id', 'channel', 'status'], name='notificatio_organiz_57496a_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization_id', 'channel', 'name'), name='uniq_notification_channel_org_channel_name', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('dashboard', 'Dashboard'), ('email', 'Email'), ('system', 'System')], default='dashboard', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('suppressed', 'Suppressed')], default='pending', max_length=16)),
                ('external_message_id', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=255)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
            ],
            options={
                'db_table': 'notifications_delivery',
            },
        ),
        migrations.CreateModel(
            name='NotificationDigest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('built', 'Built'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('notification_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_digests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_digest',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notification_type', models.CharField(blank=True, choices=[('hot_lead', 'Hot lead'), ('call_requested', 'Call requested'), ('urgent_ticket', 'Urgent ticket'), ('task_due', 'Task due'), ('task_overdue', 'Task overdue'), ('ai_failure', 'AI failure'), ('whatsapp_failure', 'WhatsApp failure'), ('system_alert', 'System alert'), ('daily_digest', 'Daily digest')], max_length=32)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('dashboard', 'Dashboard'), ('email', 'Email'), ('system', 'System')], default='whatsapp', max_length=16)),
                ('is_enabled', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('max_per_hour', models.PositiveSmallIntegerField(default=5)),
                ('digest_only', models.BooleanField(default=False)),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_preference',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='notificatio_organiz_97c774_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization_id', 'recipient_user'], name='notificatio_organiz_a05d14_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization_id', 'type'], name='notificatio_organiz_699081_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization_id', 'priority'], name='notificatio_organiz_c7d942_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization_id', 'status'], name='notificatio_organiz_5225fc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization_id', 'resource_type', 'resource_id'], name='notificatio_organiz_d8f7c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('deduplication_key__gt', '')), fields=('organization_id', 'deduplication_key'), name='uniq_notification_org_dedupe'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='notificatio_organiz_a86a94_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['created_at'], name='notificatio_created_b39031_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['organization_id', 'notification'], name='notificatio_organiz_296ff9_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['organization_id', 'channel'], name='notificatio_organiz_b618c9_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['organization_id', 'status'], name='notificatio_organiz_01c71b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['external_message_id'], name='notificatio_externa_a78bef_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('organization_id', 'idempotency_key'), name='uniq_notification_delivery_org_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'sent')), fields=('notification', 'channel'), name='uniq_sent_delivery_notification_channel'),
        ),
        migrations.AddIndex(
            model_name='notificationdigest',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='notificatio_organiz_3e3665_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdigest',
            index=models.Index(fields=['created_at'], name='notificatio_created_1465db_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdigest',
            index=models.Index(fields=['organization_id', 'recipient_user', 'period_start', 'period_end'], name='notificatio_organiz_114d32_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdigest',
            index=models.Index(fields=['organization_id', 'status'], name='notificatio_organiz_9dd136_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationdigest',
            constraint=models.UniqueConstraint(fields=('organization_id', 'recipient_user', 'period_start', 'period_end'), name='uniq_notification_digest_org_user_period'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='notificatio_organiz_353364_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['created_at'], name='notificatio_created_674fe1_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['organization_id', 'recipient_user'], name='notificatio_organiz_2e54ce_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['organization_id', 'channel'], name='notificatio_organiz_ce2cd4_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.UniqueConstraint(fields=('organization_id', 'recipient_user', 'notification_type', 'channel'), name='uniq_notification_preference_org_user_type_channel', nulls_distinct=False),
        ),
    ]
