# Generated by Django 5.2.15 on 2026-06-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_alter_aievalcase_purpose_alter_aimodelconfig_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aievalcase',
            name='purpose',
            field=models.CharField(choices=[('sales_reply', 'Sales reply'), ('support_reply', 'Support reply'), ('lead_scoring', 'Lead scoring'), ('task_extraction', 'Task extraction'), ('audio_transcription', 'Audio transcription'), ('conversation_summary', 'Conversation summary'), ('image_generation', 'Image generation'), ('embedding', 'Embedding'), ('risk_classification', 'Risk classification'), ('audio_ticket_extraction', 'Audio ticket extraction'), ('assistant_reply', 'Assistant reply'), ('document_draft', 'Document draft'), ('memory_extraction', 'Memory extraction'), ('project_brief', 'Project brief'), ('prospect_qualification', 'Prospect qualification'), ('outreach_opener', 'Outreach opener'), ('outreach_email', 'Outreach email'), ('outreach_reply', 'Outreach reply'), ('reply_intent', 'Reply intent')], max_length=48),
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='purpose',
            field=models.CharField(choices=[('sales_reply', 'Sales reply'), ('support_reply', 'Support reply'), ('lead_scoring', 'Lead scoring'), ('task_extraction', 'Task extraction'), ('audio_transcription', 'Audio transcription'), ('conversation_summary', 'Conversation summary'), ('image_generation', 'Image generation'), ('embedding', 'Embedding'), ('risk_classification', 'Risk classification'), ('audio_ticket_extraction', 'Audio ticket extraction'), ('assistant_reply', 'Assistant reply'), ('document_draft', 'Document draft'), ('memory_extraction', 'Memory extraction'), ('project_brief', 'Project brief'), ('prospect_qualification', 'Prospect qualification'), ('outreach_opener', 'Outreach opener'), ('outreach_email', 'Outreach email'), ('outreach_reply', 'Outreach reply'), ('reply_intent', 'Reply intent')], max_length=48),
        ),
        migrations.AlterField(
            model_name='aiprompt',
            name='purpose',
            field=models.CharField(choices=[('sales_reply', 'Sales reply'), ('support_reply', 'Support reply'), ('lead_scoring', 'Lead scoring'), ('task_extraction', 'Task extraction'), ('audio_transcription', 'Audio transcription'), ('conversation_summary', 'Conversation summary'), ('image_generation', 'Image generation'), ('embedding', 'Embedding'), ('risk_classification', 'Risk classification'), ('audio_ticket_extraction', 'Audio ticket extraction'), ('assistant_reply', 'Assistant reply'), ('document_draft', 'Document draft'), ('memory_extraction', 'Memory extraction'), ('project_brief', 'Project brief'), ('prospect_qualification', 'Prospect qualification'), ('outreach_opener', 'Outreach opener'), ('outreach_email', 'Outreach email'), ('outreach_reply', 'Outreach reply'), ('reply_intent', 'Reply intent')], max_length=48),
        ),
        migrations.AlterField(
            model_name='airun',
            name='purpose',
            field=models.CharField(choices=[('sales_reply', 'Sales reply'), ('support_reply', 'Support reply'), ('lead_scoring', 'Lead scoring'), ('task_extraction', 'Task extraction'), ('audio_transcription', 'Audio transcription'), ('conversation_summary', 'Conversation summary'), ('image_generation', 'Image generation'), ('embedding', 'Embedding'), ('risk_classification', 'Risk classification'), ('audio_ticket_extraction', 'Audio ticket extraction'), ('assistant_reply', 'Assistant reply'), ('document_draft', 'Document draft'), ('memory_extraction', 'Memory extraction'), ('project_brief', 'Project brief'), ('prospect_qualification', 'Prospect qualification'), ('outreach_opener', 'Outreach opener'), ('outreach_email', 'Outreach email'), ('outreach_reply', 'Outreach reply'), ('reply_intent', 'Reply intent')], max_length=48),
        ),
        migrations.AlterField(
            model_name='aiusagerecord',
            name='purpose',
            field=models.CharField(choices=[('sales_reply', 'Sales reply'), ('support_reply', 'Support reply'), ('lead_scoring', 'Lead scoring'), ('task_extraction', 'Task extraction'), ('audio_transcription', 'Audio transcription'), ('conversation_summary', 'Conversation summary'), ('image_generation', 'Image generation'), ('embedding', 'Embedding'), ('risk_classification', 'Risk classification'), ('audio_ticket_extraction', 'Audio ticket extraction'), ('assistant_reply', 'Assistant reply'), ('document_draft', 'Document draft'), ('memory_extraction', 'Memory extraction'), ('project_brief', 'Project brief'), ('prospect_qualification', 'Prospect qualification'), ('outreach_opener', 'Outreach opener'), ('outreach_email', 'Outreach email'), ('outreach_reply', 'Outreach reply'), ('reply_intent', 'Reply intent')], max_length=48),
        ),
    ]
