# Generated by Django 5.2.15 on 2026-06-12 17:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('conversations', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPlaybook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('key', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('archived', 'Archived')], default='active', max_length=16)),
                ('trigger_intents', models.JSONField(blank=True, default=list)),
                ('content', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'sales_playbook',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='sales_playb_organiz_b8553c_idx'), models.Index(fields=['created_at'], name='sales_playb_created_690233_idx'), models.Index(fields=['organization_id', 'status'], name='sales_playb_organiz_cddec2_idx'), models.Index(fields=['organization_id', 'key'], name='sales_playb_organiz_bd08ec_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization_id', 'key'), name='uniq_sales_playbook_org_key', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='SalesCallRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('owner_notified', 'Owner notified'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='requested', max_length=32)),
                ('requested_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('owner_notified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_call_requests', to='contacts.contact')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_call_requests', to='conversations.conversation')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_requests', to='leads.lead')),
            ],
            options={
                'db_table': 'sales_call_request',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='sales_call__organiz_5612c8_idx'), models.Index(fields=['created_at'], name='sales_call__created_04e934_idx'), models.Index(fields=['organization_id', 'status'], name='sales_call__organiz_f577d5_idx'), models.Index(fields=['organization_id', 'lead'], name='sales_call__organiz_ad38de_idx'), models.Index(fields=['organization_id', 'contact'], name='sales_call__organiz_a5ff8d_idx'), models.Index(fields=['organization_id', 'scheduled_at'], name='sales_call__organiz_3c2771_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('requested', 'owner_notified', 'scheduled'))), fields=('organization_id', 'lead'), name='uniq_open_call_request_org_lead')],
            },
        ),
        migrations.CreateModel(
            name='SalesFollowup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=255)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_followups', to='contacts.contact')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_followups', to='conversations.conversation')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_followups', to='leads.lead')),
            ],
            options={
                'db_table': 'sales_followup',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='sales_follo_organiz_2001ea_idx'), models.Index(fields=['created_at'], name='sales_follo_created_be6a75_idx'), models.Index(fields=['organization_id', 'lead'], name='sales_follo_organiz_5f3a3a_idx'), models.Index(fields=['organization_id', 'status', 'due_at'], name='sales_follo_organiz_22093f_idx'), models.Index(fields=['organization_id', 'contact'], name='sales_follo_organiz_49c72c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('organization_id', 'idempotency_key'), name='uniq_sales_followup_org_idempotency_key')],
            },
        ),
        migrations.CreateModel(
            name='SalesObjection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('objection_type', models.CharField(choices=[('price', 'Price'), ('time', 'Time'), ('trust', 'Trust'), ('need', 'Need'), ('not_interested', 'Not interested'), ('other', 'Other')], default='other', max_length=32)),
                ('summary', models.TextField(blank=True)),
                ('raw_text', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_objections', to='contacts.contact')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_objections', to='conversations.conversation')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objections', to='leads.lead')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_objections', to='conversations.message')),
            ],
            options={
                'db_table': 'sales_objection',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='sales_objec_organiz_bff848_idx'), models.Index(fields=['created_at'], name='sales_objec_created_fb603a_idx'), models.Index(fields=['organization_id', 'lead'], name='sales_objec_organiz_98344d_idx'), models.Index(fields=['organization_id', 'objection_type'], name='sales_objec_organiz_75ee43_idx'), models.Index(fields=['organization_id', 'message'], name='sales_objec_organiz_14786a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('message__isnull', False)), fields=('organization_id', 'lead', 'objection_type', 'message'), name='uniq_sales_objection_org_lead_type_message')],
            },
        ),
        migrations.CreateModel(
            name='SalesOpportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(max_length=255)),
                ('value_estimate_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('value_estimate_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('stage', models.CharField(choices=[('new', 'New'), ('qualifying', 'Qualifying'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=32)),
                ('probability', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_opportunities', to='contacts.contact')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='leads.lead')),
            ],
            options={
                'db_table': 'sales_opportunity',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='sales_oppor_organiz_cafbbc_idx'), models.Index(fields=['created_at'], name='sales_oppor_created_dfec50_idx'), models.Index(fields=['organization_id', 'stage'], name='sales_oppor_organiz_b56048_idx'), models.Index(fields=['organization_id', 'probability'], name='sales_oppor_organiz_22f703_idx'), models.Index(fields=['organization_id', 'expected_close_date'], name='sales_oppor_organiz_c4b649_idx'), models.Index(fields=['organization_id', 'lead'], name='sales_oppor_organiz_af4ef2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('probability__gte', 0), ('probability__lte', 100)), name='ck_sales_opportunity_probability_0_100'), models.CheckConstraint(condition=models.Q(('value_estimate_min__isnull', True), ('value_estimate_max__isnull', True), ('value_estimate_min__lte', models.F('value_estimate_max')), _connector='OR'), name='ck_sales_opportunity_value_range')],
            },
        ),
    ]
