# Generated by Django 5.2.15 on 2026-06-22 04:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('manual_text', 'Manual text'), ('pdf', 'PDF'), ('faq', 'FAQ'), ('conversation', 'Conversation')], max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('failed', 'Failed')], default='active', max_length=24)),
            ],
            options={
                'db_table': 'knowledge_source',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='knowledge_s_organiz_85409b_idx'), models.Index(fields=['created_at'], name='knowledge_s_created_f9b9c4_idx'), models.Index(fields=['organization_id', 'source_type', 'status'], name='knowledge_s_organiz_196b20_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization_id', 'name', 'source_type'), name='uniq_knowledge_source_org_name_type', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(max_length=255)),
                ('raw_text', models.TextField(blank=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('ingest_status', models.CharField(choices=[('pending', 'Pending'), ('chunked', 'Chunked'), ('embedded', 'Embedded'), ('failed', 'Failed')], default='pending', max_length=24)),
                ('error_message', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='knowledge.knowledgesource')),
            ],
            options={
                'db_table': 'knowledge_document',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('token_estimate', models.PositiveIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.knowledgedocument')),
            ],
            options={
                'db_table': 'knowledge_chunk',
                'ordering': ['document_id', 'chunk_index'],
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='knowledge_c_organiz_4c2916_idx'), models.Index(fields=['created_at'], name='knowledge_c_created_5ec042_idx'), models.Index(fields=['organization_id', 'document'], name='knowledge_c_organiz_49f711_idx'), models.Index(fields=['content_hash'], name='knowledge_c_content_c6d808_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization_id', 'document', 'chunk_index'), name='uniq_knowledge_chunk_org_doc_index')],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='knowledge_d_organiz_24f1e7_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['created_at'], name='knowledge_d_created_596f28_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['organization_id', 'source', 'ingest_status'], name='knowledge_d_organiz_eaf4d0_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['content_hash'], name='knowledge_d_content_979d1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgedocument',
            constraint=models.UniqueConstraint(fields=('organization_id', 'source', 'content_hash'), name='uniq_knowledge_doc_org_source_hash', nulls_distinct=False),
        ),
    ]
