# Generated by Django 5.2.15 on 2026-06-12 17:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('display_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('onboarding', 'Onboarding'), ('delinquent', 'Delinquent'), ('archived', 'Archived')], default='active', max_length=16)),
                ('service_plan', models.CharField(blank=True, max_length=120)),
                ('support_level', models.CharField(choices=[('standard', 'Standard'), ('priority', 'Priority'), ('vip', 'VIP'), ('internal', 'Internal')], default='standard', max_length=16)),
                ('onboarding_status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='not_started', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='contacts.company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='contacts.contact')),
            ],
            options={
                'db_table': 'clients_client',
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('technical', 'Technical'), ('billing', 'Billing'), ('user', 'User'), ('other', 'Other')], default='user', max_length=16)),
                ('is_primary', models.BooleanField(default=False)),
                ('can_request_support', models.BooleanField(default=True)),
                ('receives_notifications', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_contacts', to='clients.client')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_links', to='contacts.contact')),
            ],
            options={
                'db_table': 'clients_client_contact',
            },
        ),
        migrations.CreateModel(
            name='ClientService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('crm', 'CRM'), ('automation', 'Automation'), ('whatsapp', 'WhatsApp'), ('web', 'Web'), ('integration', 'Integration'), ('support', 'Support'), ('consulting', 'Consulting'), ('other', 'Other')], default='other', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('pending', 'Pending')], default='active', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clients.client')),
            ],
            options={
                'db_table': 'clients_client_service',
            },
        ),
        migrations.CreateModel(
            name='ClientStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(max_length=16)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('changed_by_id', models.UUIDField(blank=True, null=True)),
                ('changed_by_type', models.CharField(choices=[('user', 'User'), ('system', 'System'), ('automation', 'Automation'), ('worker', 'Worker'), ('ai_agent', 'AI agent')], default='system', max_length=16)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='clients.client')),
            ],
            options={
                'db_table': 'clients_client_status_history',
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='clients_cli_organiz_fcc2ba_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['created_at'], name='clients_cli_created_4ff9ec_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['organization_id', 'status'], name='clients_cli_organiz_bb5819_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['organization_id', 'support_level'], name='clients_cli_organiz_52753f_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['organization_id', 'contact'], name='clients_cli_organiz_25bb43_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'active')), fields=('organization_id', 'contact'), name='uniq_active_client_per_contact'),
        ),
        migrations.AddIndex(
            model_name='clientcontact',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='clients_cli_organiz_e9355b_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcontact',
            index=models.Index(fields=['created_at'], name='clients_cli_created_dc43b1_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcontact',
            index=models.Index(fields=['organization_id', 'client'], name='clients_cli_organiz_704c20_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcontact',
            index=models.Index(fields=['organization_id', 'contact'], name='clients_cli_organiz_616b8f_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcontact',
            index=models.Index(fields=['organization_id', 'can_request_support'], name='clients_cli_organiz_3be328_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientcontact',
            constraint=models.UniqueConstraint(fields=('organization_id', 'client', 'contact'), name='uniq_client_contact_org_client_contact'),
        ),
        migrations.AddIndex(
            model_name='clientservice',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='clients_cli_organiz_17ab94_idx'),
        ),
        migrations.AddIndex(
            model_name='clientservice',
            index=models.Index(fields=['created_at'], name='clients_cli_created_775b9f_idx'),
        ),
        migrations.AddIndex(
            model_name='clientservice',
            index=models.Index(fields=['organization_id', 'client'], name='clients_cli_organiz_6f560d_idx'),
        ),
        migrations.AddIndex(
            model_name='clientservice',
            index=models.Index(fields=['organization_id', 'service_type', 'status'], name='clients_cli_organiz_7dc257_idx'),
        ),
        migrations.AddIndex(
            model_name='clientstatushistory',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='clients_cli_organiz_05ad1a_idx'),
        ),
        migrations.AddIndex(
            model_name='clientstatushistory',
            index=models.Index(fields=['created_at'], name='clients_cli_created_4da91b_idx'),
        ),
        migrations.AddIndex(
            model_name='clientstatushistory',
            index=models.Index(fields=['client', 'created_at'], name='clients_cli_client__dc8bc4_idx'),
        ),
    ]
