# Generated by Django 5.2.15 on 2026-06-11 03:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('dashboard', 'Dashboard'), ('system', 'System')], max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('closed', 'Closed'), ('archived', 'Archived')], default='open', max_length=32)),
                ('mode', models.CharField(choices=[('sales_ai', 'Sales AI'), ('support_ai', 'Support AI'), ('internal_assistant', 'Internal assistant'), ('manual', 'Manual'), ('paused', 'Paused'), ('blocked', 'Blocked')], default='manual', max_length=32)),
                ('ai_enabled', models.BooleanField(default=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_inbound_at', models.DateTimeField(blank=True, null=True)),
                ('last_outbound_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='contacts.contact')),
            ],
            options={
                'db_table': 'conversations_conversation',
            },
        ),
        migrations.CreateModel(
            name='ConversationMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('memory_type', models.CharField(choices=[('preference', 'Preference'), ('pain_point', 'Pain point'), ('technical_context', 'Technical context'), ('commercial_context', 'Commercial context'), ('support_context', 'Support context'), ('objection', 'Objection'), ('commitment', 'Commitment')], max_length=32)),
                ('content', models.TextField()),
                ('importance', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('embedding_id', models.UUIDField(blank=True, null=True)),
                ('source_message_id', models.UUIDField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memories', to='contacts.contact')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='conversations.conversation')),
            ],
            options={
                'db_table': 'conversations_conversation_memory',
            },
        ),
        migrations.CreateModel(
            name='ConversationSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField()),
                ('summary_type', models.CharField(choices=[('short', 'Short'), ('technical', 'Technical'), ('sales', 'Sales'), ('support', 'Support'), ('daily', 'Daily'), ('handoff', 'Handoff')], default='short', max_length=32)),
                ('source_message_from_id', models.UUIDField(blank=True, null=True)),
                ('source_message_to_id', models.UUIDField(blank=True, null=True)),
                ('created_by_ai_run_id', models.UUIDField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='conversations.conversation')),
            ],
            options={
                'db_table': 'conversations_conversation_summary',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('internal', 'Internal'), ('system', 'System')], max_length=16)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('sticker', 'Sticker'), ('location', 'Location'), ('contact_card', 'Contact card'), ('system', 'System')], default='text', max_length=32)),
                ('body', models.TextField(blank=True)),
                ('normalized_text', models.TextField(blank=True)),
                ('external_message_id', models.CharField(blank=True, max_length=255)),
                ('external_timestamp', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='received', max_length=16)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='contacts.contact')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
            ],
            options={
                'db_table': 'conversations_message',
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('media_asset_id', models.UUIDField(blank=True, null=True)),
                ('external_media_id', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='conversations.message')),
            ],
            options={
                'db_table': 'conversations_message_attachment',
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='conversatio_organiz_bb6739_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['created_at'], name='conversatio_created_5a5006_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['organization_id', 'status', 'mode'], name='conversatio_organiz_771b65_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['organization_id', 'last_message_at'], name='conversatio_organiz_9abf15_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['organization_id', 'contact', 'channel'], name='conversatio_organiz_ee37ad_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['organization_id', 'assigned_user'], name='conversatio_organiz_e4ac8f_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmemory',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='conversatio_organiz_03bc41_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmemory',
            index=models.Index(fields=['created_at'], name='conversatio_created_13debe_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmemory',
            index=models.Index(fields=['conversation', 'created_at'], name='conversatio_convers_1cb79a_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmemory',
            index=models.Index(fields=['organization_id', 'contact', 'memory_type'], name='conversatio_organiz_fd808c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmemory',
            index=models.Index(fields=['expires_at'], name='conversatio_expires_39e491_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationmemory',
            constraint=models.CheckConstraint(condition=models.Q(('importance__gte', 1), ('importance__lte', 5)), name='ck_conversation_memory_importance_range'),
        ),
        migrations.AddIndex(
            model_name='conversationsummary',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='conversatio_organiz_cff14f_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsummary',
            index=models.Index(fields=['created_at'], name='conversatio_created_d4b577_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsummary',
            index=models.Index(fields=['conversation', 'created_at'], name='conversatio_convers_a93a1a_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsummary',
            index=models.Index(fields=['organization_id', 'summary_type'], name='conversatio_organiz_654d56_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='conversatio_organiz_ecb9a4_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='conversatio_created_792fff_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['organization_id', 'conversation', 'created_at'], name='conversatio_organiz_20ce4e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['organization_id', 'contact', 'created_at'], name='conversatio_organiz_0b3f81_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['organization_id', 'external_message_id'], name='conversatio_organiz_aece7c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['organization_id', 'direction'], name='conversatio_organiz_db206a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['organization_id', 'status'], name='conversatio_organiz_8a9604_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='conversatio_convers_4b968d_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('external_message_id__gt', '')), fields=('organization_id', 'external_message_id'), name='uniq_message_org_external_id'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='conversatio_organiz_564d56_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['created_at'], name='conversatio_created_2735e0_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['message'], name='conversatio_message_8aae5f_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['organization_id', 'external_media_id'], name='conversatio_organiz_01f35e_idx'),
        ),
    ]
