# Generated by Django 5.2.15 on 2026-06-12 17:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('message_received', 'Message received'), ('lead_score_changed', 'Lead score changed'), ('lead_became_hot', 'Lead became hot'), ('ticket_created', 'Ticket created'), ('task_due', 'Task due'), ('task_overdue', 'Task overdue'), ('audio_transcribed', 'Audio transcribed'), ('client_registered', 'Client registered'), ('conversation_paused', 'Conversation paused')], max_length=48)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('is_enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'automations_rule',
            },
        ),
        migrations.CreateModel(
            name='AutomationCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('condition_type', models.CharField(default='field', max_length=64)),
                ('field_path', models.CharField(max_length=255)),
                ('operator', models.CharField(default='eq', max_length=32)),
                ('expected_value', models.JSONField(blank=True, null=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_rows', to='automations.automationrule')),
            ],
            options={
                'db_table': 'automations_condition',
            },
        ),
        migrations.CreateModel(
            name='AutomationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('action_type', models.CharField(choices=[('send_whatsapp_message', 'Send WhatsApp message'), ('notify_owner', 'Notify owner'), ('create_task', 'Create task'), ('update_lead_stage', 'Update lead stage'), ('create_ticket', 'Create ticket'), ('pause_ai', 'Pause AI'), ('assign_user', 'Assign user'), ('schedule_followup', 'Schedule followup')], max_length=48)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('required_permission', models.CharField(blank=True, max_length=120)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=30)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_rows', to='automations.automationrule')),
            ],
            options={
                'db_table': 'automations_action',
            },
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('trigger_type', models.CharField(choices=[('message_received', 'Message received'), ('lead_score_changed', 'Lead score changed'), ('lead_became_hot', 'Lead became hot'), ('ticket_created', 'Ticket created'), ('task_due', 'Task due'), ('task_overdue', 'Task overdue'), ('audio_transcribed', 'Audio transcribed'), ('client_registered', 'Client registered'), ('conversation_paused', 'Conversation paused')], max_length=48)),
                ('trigger_event_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('skipped', 'Skipped'), ('success', 'Success'), ('partially_failed', 'Partially failed'), ('failed', 'Failed'), ('duplicate', 'Duplicate')], default='running', max_length=32)),
                ('trigger_payload', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='automations.automationrule')),
            ],
            options={
                'db_table': 'automations_run',
            },
        ),
        migrations.CreateModel(
            name='AutomationRunStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('step_type', models.CharField(choices=[('condition', 'Condition'), ('action', 'Action')], max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('skipped', 'Skipped'), ('success', 'Success'), ('failed', 'Failed'), ('blocked', 'Blocked')], default='pending', max_length=16)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('output_payload', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_steps', to='automations.automationaction')),
                ('automation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='automations.automationrun')),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_steps', to='automations.automationcondition')),
            ],
            options={
                'db_table': 'automations_run_step',
            },
        ),
        migrations.CreateModel(
            name='AutomationTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('trigger_type', models.CharField(choices=[('message_received', 'Message received'), ('lead_score_changed', 'Lead score changed'), ('lead_became_hot', 'Lead became hot'), ('ticket_created', 'Ticket created'), ('task_due', 'Task due'), ('task_overdue', 'Task overdue'), ('audio_transcribed', 'Audio transcribed'), ('client_registered', 'Client registered'), ('conversation_paused', 'Conversation paused')], max_length=48)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='automations.automationrule')),
            ],
            options={
                'db_table': 'automations_trigger',
            },
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='automations_organiz_62901c_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['created_at'], name='automations_created_5b73ba_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['organization_id', 'trigger_type'], name='automations_organiz_a0d948_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['organization_id', 'is_enabled'], name='automations_organiz_a86928_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['organization_id', 'priority'], name='automations_organiz_8b7d5d_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['created_by'], name='automations_created_2848fc_idx'),
        ),
        migrations.AddIndex(
            model_name='automationcondition',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='automations_organiz_430219_idx'),
        ),
        migrations.AddIndex(
            model_name='automationcondition',
            index=models.Index(fields=['created_at'], name='automations_created_fbdcf2_idx'),
        ),
        migrations.AddIndex(
            model_name='automationcondition',
            index=models.Index(fields=['organization_id', 'rule', 'order'], name='automations_organiz_1e1813_idx'),
        ),
        migrations.AddIndex(
            model_name='automationaction',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='automations_organiz_99f2d0_idx'),
        ),
        migrations.AddIndex(
            model_name='automationaction',
            index=models.Index(fields=['created_at'], name='automations_created_20ac13_idx'),
        ),
        migrations.AddIndex(
            model_name='automationaction',
            index=models.Index(fields=['organization_id', 'rule', 'order'], name='automations_organiz_70055b_idx'),
        ),
        migrations.AddIndex(
            model_name='automationaction',
            index=models.Index(fields=['organization_id', 'action_type'], name='automations_organiz_3c7a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrun',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='automations_organiz_97464f_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrun',
            index=models.Index(fields=['created_at'], name='automations_created_e22917_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrun',
            index=models.Index(fields=['organization_id', 'rule'], name='automations_organiz_611627_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrun',
            index=models.Index(fields=['organization_id', 'trigger_type'], name='automations_organiz_dfc919_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrun',
            index=models.Index(fields=['organization_id', 'status'], name='automations_organiz_29e863_idx'),
        ),
        migrations.AddConstraint(
            model_name='automationrun',
            constraint=models.UniqueConstraint(condition=models.Q(('trigger_event_id__gt', '')), fields=('organization_id', 'rule', 'trigger_event_id'), name='uniq_automation_run_rule_trigger_event'),
        ),
        migrations.AddIndex(
            model_name='automationrunstep',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='automations_organiz_4d4173_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrunstep',
            index=models.Index(fields=['created_at'], name='automations_created_8066e5_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrunstep',
            index=models.Index(fields=['organization_id', 'automation_run'], name='automations_organiz_c8fdc5_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrunstep',
            index=models.Index(fields=['organization_id', 'status'], name='automations_organiz_2ea279_idx'),
        ),
        migrations.AddIndex(
            model_name='automationtrigger',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='automations_organiz_39ec17_idx'),
        ),
        migrations.AddIndex(
            model_name='automationtrigger',
            index=models.Index(fields=['created_at'], name='automations_created_fdb744_idx'),
        ),
        migrations.AddIndex(
            model_name='automationtrigger',
            index=models.Index(fields=['organization_id', 'rule'], name='automations_organiz_17c103_idx'),
        ),
        migrations.AddIndex(
            model_name='automationtrigger',
            index=models.Index(fields=['organization_id', 'trigger_type'], name='automations_organiz_a8924d_idx'),
        ),
    ]
