# Generated by Django 6.0.6 on 2026-06-11 02:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(max_length=80)),
                ('operation', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=32)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=128)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='integration_organiz_c5f7ee_idx'), models.Index(fields=['created_at'], name='integration_created_11c2b2_idx'), models.Index(fields=['organization_id', 'provider', 'operation'], name='integration_organiz_38da9f_idx'), models.Index(fields=['status', 'created_at'], name='integration_status_9ad8c5_idx')],
            },
        ),
    ]
