# Generated by Django 5.2.15 on 2026-06-11 03:01

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('key', models.CharField(max_length=255)),
                ('scope', models.CharField(max_length=120)),
                ('request_hash', models.CharField(max_length=128)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='processing', max_length=32)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'core_idempotency_key',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='core_idempo_organiz_42785f_idx'), models.Index(fields=['created_at'], name='core_idempo_created_2e21e8_idx'), models.Index(fields=['status', 'expires_at'], name='core_idempo_status_a182d2_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization_id', 'scope', 'key'), name='uniq_idempotency_org_scope_key', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('event_type', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('dead_letter', 'Dead letter')], default='pending', max_length=32)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'core_outbox_event',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='core_outbox_organiz_e853fb_idx'), models.Index(fields=['created_at'], name='core_outbox_created_026651_idx'), models.Index(fields=['status', 'available_at'], name='core_outbox_status_b3ba4c_idx'), models.Index(fields=['event_type'], name='core_outbox_event_t_c640d1_idx'), models.Index(fields=['organization_id', 'status'], name='core_outbox_organiz_a8c321_idx')],
            },
        ),
    ]
