# Generated by Django 5.2.15 on 2026-06-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_organiz_fdb8aa_idx',
            old_name='audit_audit_organiz_ab5327_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_organiz_213e35_idx',
            old_name='audit_audit_organiz_b20932_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_resourc_323309_idx',
            old_name='audit_audit_resourc_2ab5ff_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_created_11a5b8_idx',
            old_name='audit_audit_created_7710b7_idx',
        ),
        migrations.AddField(
            model_name='auditevent',
            name='changes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['organization_id', 'event_type'], name='audit_audit_organiz_cc6b0c_idx'),
        ),
        migrations.AlterModelTable(
            name='auditevent',
            table='audit_audit_event',
        ),
    ]
