# Generated by Django 5.2.15 on 2026-06-12 17:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('owner_type', models.CharField(max_length=64)),
                ('owner_id', models.UUIDField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('storage_key', models.CharField(blank=True, max_length=512)),
                ('storage_provider', models.CharField(choices=[('local', 'Local private'), ('s3', 'S3 compatible')], default='local', max_length=16)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('dashboard', 'Dashboard'), ('ai_generated', 'AI generated'), ('system', 'System')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('stored', 'Stored'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='pending', max_length=16)),
            ],
            options={
                'db_table': 'media_media_asset',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='media_media_organiz_12cb29_idx'), models.Index(fields=['created_at'], name='media_media_created_c91083_idx'), models.Index(fields=['organization_id', 'owner_type', 'owner_id'], name='media_media_organiz_90bb65_idx'), models.Index(fields=['organization_id', 'source'], name='media_media_organiz_4f1d23_idx'), models.Index(fields=['organization_id', 'status'], name='media_media_organiz_dcddc1_idx'), models.Index(fields=['organization_id', 'mime_type'], name='media_media_organiz_0d86c5_idx'), models.Index(fields=['checksum'], name='media_media_checksu_64aea9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImageGenerationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('prompt', models.TextField()),
                ('final_prompt', models.TextField(blank=True)),
                ('image_type', models.CharField(choices=[('proposal_cover', 'Proposal cover'), ('instagram_post', 'Instagram post'), ('instagram_story', 'Instagram story'), ('banner', 'Banner'), ('thumbnail', 'Thumbnail'), ('ad_creative', 'Ad creative'), ('client_mockup', 'Client mockup')], max_length=32)),
                ('aspect_ratio', models.CharField(choices=[('1:1', '1:1'), ('4:5', '4:5'), ('9:16', '9:16'), ('16:9', '16:9'), ('3:2', '3:2')], default='1:1', max_length=8)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('ai_run_id', models.UUIDField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_generation_requests', to=settings.AUTH_USER_MODEL)),
                ('result_media_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_generation_requests', to='media.mediaasset')),
            ],
            options={
                'db_table': 'media_image_generation_request',
            },
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('prompt', models.TextField(blank=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('image_generation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='media.imagegenerationrequest')),
                ('media_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_image_records', to='media.mediaasset')),
            ],
            options={
                'db_table': 'media_generated_image',
            },
        ),
        migrations.CreateModel(
            name='MediaProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('job_type', models.CharField(choices=[('download', 'Download'), ('validate', 'Validate'), ('transcribe', 'Transcribe'), ('extract_ticket', 'Extract ticket'), ('generate_image', 'Generate image'), ('store_generated_image', 'Store generated image'), ('cleanup', 'Cleanup')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('available_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('media_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='media.mediaasset')),
            ],
            options={
                'db_table': 'media_processing_job',
            },
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('language', models.CharField(default='es', max_length=16)),
                ('text', models.TextField(blank=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('duration_seconds', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('ai_run_id', models.UUIDField(blank=True, null=True)),
                ('media_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='media.mediaasset')),
            ],
            options={
                'db_table': 'media_transcription',
            },
        ),
        migrations.AddIndex(
            model_name='imagegenerationrequest',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='media_image_organiz_49bd83_idx'),
        ),
        migrations.AddIndex(
            model_name='imagegenerationrequest',
            index=models.Index(fields=['created_at'], name='media_image_created_fdef7c_idx'),
        ),
        migrations.AddIndex(
            model_name='imagegenerationrequest',
            index=models.Index(fields=['organization_id', 'status'], name='media_image_organiz_a4c528_idx'),
        ),
        migrations.AddIndex(
            model_name='imagegenerationrequest',
            index=models.Index(fields=['organization_id', 'image_type'], name='media_image_organiz_387a26_idx'),
        ),
        migrations.AddIndex(
            model_name='imagegenerationrequest',
            index=models.Index(fields=['organization_id', 'created_by'], name='media_image_organiz_a8da49_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedimage',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='media_gener_organiz_f66a49_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedimage',
            index=models.Index(fields=['created_at'], name='media_gener_created_c4e989_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedimage',
            index=models.Index(fields=['organization_id', 'image_generation_request'], name='media_gener_organiz_973a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedimage',
            index=models.Index(fields=['organization_id', 'media_asset'], name='media_gener_organiz_9f4c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaprocessingjob',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='media_proce_organiz_b742a7_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaprocessingjob',
            index=models.Index(fields=['created_at'], name='media_proce_created_2420bc_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaprocessingjob',
            index=models.Index(fields=['organization_id', 'media_asset'], name='media_proce_organiz_ee0e2d_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaprocessingjob',
            index=models.Index(fields=['organization_id', 'job_type', 'status'], name='media_proce_organiz_40f568_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaprocessingjob',
            index=models.Index(fields=['available_at'], name='media_proce_availab_bbeb2a_idx'),
        ),
        migrations.AddIndex(
            model_name='transcription',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='media_trans_organiz_f59fab_idx'),
        ),
        migrations.AddIndex(
            model_name='transcription',
            index=models.Index(fields=['created_at'], name='media_trans_created_3a03a8_idx'),
        ),
        migrations.AddIndex(
            model_name='transcription',
            index=models.Index(fields=['organization_id', 'media_asset'], name='media_trans_organiz_d62ecc_idx'),
        ),
        migrations.AddIndex(
            model_name='transcription',
            index=models.Index(fields=['organization_id', 'status'], name='media_trans_organiz_33813f_idx'),
        ),
    ]
