# Generated by Django 5.2.15 on 2026-06-12 17:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('won', 'Won'), ('lost', 'Lost'), ('unqualified', 'Unqualified'), ('nurturing', 'Nurturing'), ('archived', 'Archived')], default='active', max_length=32)),
                ('stage', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualifying', 'Qualifying'), ('warm', 'Warm'), ('hot', 'Hot'), ('call_requested', 'Call requested'), ('call_scheduled', 'Call scheduled'), ('proposal_pending', 'Proposal pending'), ('won', 'Won'), ('lost', 'Lost'), ('nurturing', 'Nurturing'), ('unqualified', 'Unqualified')], default='new', max_length=32)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('temperature', models.CharField(choices=[('cold', 'Cold'), ('warm', 'Warm'), ('hot', 'Hot'), ('critical', 'Critical')], default='cold', max_length=16)),
                ('service_interest', models.CharField(blank=True, max_length=255)),
                ('budget_signal', models.CharField(choices=[('none', 'None'), ('unknown', 'Unknown'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('confirmed', 'Confirmed')], default='unknown', max_length=16)),
                ('urgency', models.CharField(choices=[('unknown', 'Unknown'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='unknown', max_length=16)),
                ('authority_signal', models.CharField(choices=[('unknown', 'Unknown'), ('influencer', 'Influencer'), ('decision_maker', 'Decision maker'), ('likely_decision_maker', 'Likely decision maker')], default='unknown', max_length=32)),
                ('pain_points', models.JSONField(blank=True, default=list)),
                ('technical_needs', models.JSONField(blank=True, default=list)),
                ('business_needs', models.JSONField(blank=True, default=list)),
                ('next_best_action', models.CharField(blank=True, max_length=255)),
                ('last_scored_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='contacts.contact')),
            ],
            options={
                'db_table': 'leads_lead',
            },
        ),
        migrations.CreateModel(
            name='LeadScoreSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('score', models.PositiveSmallIntegerField()),
                ('temperature', models.CharField(choices=[('cold', 'Cold'), ('warm', 'Warm'), ('hot', 'Hot'), ('critical', 'Critical')], max_length=16)),
                ('reasoning_summary', models.TextField(blank=True)),
                ('factors', models.JSONField(default=dict)),
                ('ai_run_id', models.UUIDField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_snapshots', to='leads.lead')),
            ],
            options={
                'db_table': 'leads_lead_score_snapshot',
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('manual', 'Manual'), ('website', 'Website'), ('referral', 'Referral'), ('campaign', 'Campaign'), ('import', 'Import'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('source_detail', models.CharField(blank=True, max_length=255)),
                ('campaign', models.CharField(blank=True, max_length=255)),
                ('channel', models.CharField(blank=True, max_length=32)),
                ('first_touch_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_touch_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_sources', to='conversations.conversation')),
                ('first_touch_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_sources', to='conversations.message')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='leads.lead')),
            ],
            options={
                'db_table': 'leads_lead_source',
            },
        ),
        migrations.CreateModel(
            name='LeadStageHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('from_stage', models.CharField(blank=True, max_length=32)),
                ('to_stage', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualifying', 'Qualifying'), ('warm', 'Warm'), ('hot', 'Hot'), ('call_requested', 'Call requested'), ('call_scheduled', 'Call scheduled'), ('proposal_pending', 'Proposal pending'), ('won', 'Won'), ('lost', 'Lost'), ('nurturing', 'Nurturing'), ('unqualified', 'Unqualified')], max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('changed_by_id', models.UUIDField(blank=True, null=True)),
                ('changed_by_type', models.CharField(choices=[('user', 'User'), ('ai_agent', 'AI agent'), ('system', 'System'), ('automation', 'Automation'), ('worker', 'Worker')], default='system', max_length=32)),
                ('ai_run_id', models.UUIDField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='leads.lead')),
            ],
            options={
                'db_table': 'leads_lead_stage_history',
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='leads_lead_organiz_f2d7e7_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='leads_lead_created_302c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization_id', 'status'], name='leads_lead_organiz_1ed3c6_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization_id', 'stage'], name='leads_lead_organiz_68aa98_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization_id', 'temperature'], name='leads_lead_organiz_62acc1_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization_id', 'score'], name='leads_lead_organiz_cbaed6_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization_id', 'contact'], name='leads_lead_organiz_88c783_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization_id', 'last_scored_at'], name='leads_lead_organiz_e2c19c_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('organization_id', 'contact'), name='uniq_active_lead_org_contact'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='ck_lead_score_0_100'),
        ),
        migrations.AddIndex(
            model_name='leadscoresnapshot',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='leads_lead__organiz_69ce6f_idx'),
        ),
        migrations.AddIndex(
            model_name='leadscoresnapshot',
            index=models.Index(fields=['created_at'], name='leads_lead__created_1d4d26_idx'),
        ),
        migrations.AddIndex(
            model_name='leadscoresnapshot',
            index=models.Index(fields=['organization_id', 'lead', 'created_at'], name='leads_lead__organiz_1db341_idx'),
        ),
        migrations.AddConstraint(
            model_name='leadscoresnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='ck_lead_snapshot_score_0_100'),
        ),
        migrations.AddIndex(
            model_name='leadsource',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='leads_lead__organiz_f06484_idx'),
        ),
        migrations.AddIndex(
            model_name='leadsource',
            index=models.Index(fields=['created_at'], name='leads_lead__created_4f0859_idx'),
        ),
        migrations.AddIndex(
            model_name='leadsource',
            index=models.Index(fields=['organization_id', 'lead'], name='leads_lead__organiz_0c577b_idx'),
        ),
        migrations.AddIndex(
            model_name='leadsource',
            index=models.Index(fields=['organization_id', 'source_type'], name='leads_lead__organiz_29858d_idx'),
        ),
        migrations.AddIndex(
            model_name='leadstagehistory',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='leads_lead__organiz_a55a42_idx'),
        ),
        migrations.AddIndex(
            model_name='leadstagehistory',
            index=models.Index(fields=['created_at'], name='leads_lead__created_5340da_idx'),
        ),
        migrations.AddIndex(
            model_name='leadstagehistory',
            index=models.Index(fields=['organization_id', 'lead', 'created_at'], name='leads_lead__organiz_4b0d44_idx'),
        ),
    ]
