# Generated by Django 5.2.15 on 2026-06-12 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('contacts', '0001_initial'),
        ('conversations', '0001_initial'),
        ('leads', '0001_initial'),
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('waiting', 'Waiting'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue'), ('snoozed', 'Snoozed')], default='pending', max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=16)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('conversation', 'Conversation'), ('lead', 'Lead'), ('ticket', 'Ticket'), ('ai_extracted', 'AI extracted'), ('automation', 'Automation'), ('system', 'System')], default='manual', max_length=32)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=255)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='clients.client')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='contacts.contact')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='conversations.conversation')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='leads.lead')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='support.supportticket')),
            ],
            options={
                'db_table': 'tasks_task',
            },
        ),
        migrations.CreateModel(
            name='TaskCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('raw_command', models.TextField()),
                ('command_type', models.CharField(choices=[('complete', 'Complete'), ('pending', 'Pending'), ('snooze', 'Snooze'), ('cancel', 'Cancel'), ('detail', 'Detail'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('parsed_command', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='received', max_length=16)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_commands', to='conversations.message')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to='tasks.task')),
            ],
            options={
                'db_table': 'tasks_task_command',
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('author_type', models.CharField(choices=[('user', 'User'), ('ai_agent', 'AI agent'), ('system', 'System'), ('worker', 'Worker')], default='user', max_length=16)),
                ('author_id', models.UUIDField(blank=True, null=True)),
                ('body', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task')),
            ],
            options={
                'db_table': 'tasks_task_comment',
            },
        ),
        migrations.CreateModel(
            name='TaskReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('remind_at', models.DateTimeField(db_index=True)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('dashboard', 'Dashboard'), ('email', 'Email'), ('system', 'System')], default='whatsapp', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('snoozed', 'Snoozed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('notification_id', models.UUIDField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='tasks.task')),
            ],
            options={
                'db_table': 'tasks_task_reminder',
            },
        ),
        migrations.CreateModel(
            name='TaskSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('conversation', 'Conversation'), ('lead', 'Lead'), ('ticket', 'Ticket'), ('ai_extracted', 'AI extracted'), ('automation', 'Automation'), ('system', 'System')], default='manual', max_length=32)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('ai_run_id', models.UUIDField(blank=True, null=True)),
                ('normalized_title', models.CharField(blank=True, max_length=255)),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_sources', to='conversations.message')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='tasks.task')),
            ],
            options={
                'db_table': 'tasks_task_source',
            },
        ),
        migrations.CreateModel(
            name='TaskStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('waiting', 'Waiting'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue'), ('snoozed', 'Snoozed')], max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('changed_by_id', models.UUIDField(blank=True, null=True)),
                ('changed_by_type', models.CharField(choices=[('user', 'User'), ('ai_agent', 'AI agent'), ('system', 'System'), ('worker', 'Worker')], default='system', max_length=16)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='tasks.task')),
            ],
            options={
                'db_table': 'tasks_task_status_history',
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='tasks_task_organiz_66808c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at'], name='tasks_task_created_be1ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['organization_id', 'status'], name='tasks_task_organiz_ab0744_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['organization_id', 'priority'], name='tasks_task_organiz_6ce07c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['organization_id', 'assigned_to'], name='tasks_task_organiz_eadc48_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['organization_id', 'due_at'], name='tasks_task_organiz_8a84e7_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['organization_id', 'contact'], name='tasks_task_organiz_17034e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['organization_id', 'lead'], name='tasks_task_organiz_52f1e9_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['organization_id', 'client'], name='tasks_task_organiz_89aac3_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['organization_id', 'ticket'], name='tasks_task_organiz_505ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['organization_id', 'conversation'], name='tasks_task_organiz_ad4acd_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['organization_id', 'source_type'], name='tasks_task_organiz_76aa65_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['organization_id', 'idempotency_key'], name='tasks_task_organiz_58d08a_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('organization_id', 'idempotency_key'), name='uniq_task_org_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status', 'completed')), models.Q(('status', 'completed'), _negated=True), _connector='OR'), name='ck_task_completed_requires_completed_at'),
        ),
        migrations.AddIndex(
            model_name='taskcommand',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='tasks_task__organiz_8ceef0_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcommand',
            index=models.Index(fields=['created_at'], name='tasks_task__created_3c0cb9_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcommand',
            index=models.Index(fields=['organization_id', 'task'], name='tasks_task__organiz_406d46_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcommand',
            index=models.Index(fields=['organization_id', 'message'], name='tasks_task__organiz_31b687_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcommand',
            index=models.Index(fields=['organization_id', 'status'], name='tasks_task__organiz_91b7b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskcommand',
            constraint=models.UniqueConstraint(condition=models.Q(('message__isnull', False)), fields=('organization_id', 'message'), name='uniq_task_command_org_message'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='tasks_task__organiz_ed461f_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['created_at'], name='tasks_task__created_247821_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['organization_id', 'task', 'created_at'], name='tasks_task__organiz_9bdd42_idx'),
        ),
        migrations.AddIndex(
            model_name='taskreminder',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='tasks_task__organiz_16bffa_idx'),
        ),
        migrations.AddIndex(
            model_name='taskreminder',
            index=models.Index(fields=['created_at'], name='tasks_task__created_12d0d6_idx'),
        ),
        migrations.AddIndex(
            model_name='taskreminder',
            index=models.Index(fields=['organization_id', 'task'], name='tasks_task__organiz_e923af_idx'),
        ),
        migrations.AddIndex(
            model_name='taskreminder',
            index=models.Index(fields=['organization_id', 'status'], name='tasks_task__organiz_23a422_idx'),
        ),
        migrations.AddIndex(
            model_name='taskreminder',
            index=models.Index(fields=['organization_id', 'remind_at'], name='tasks_task__organiz_9d6be3_idx'),
        ),
        migrations.AddIndex(
            model_name='taskreminder',
            index=models.Index(fields=['organization_id', 'channel'], name='tasks_task__organiz_1857cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskreminder',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'queued'])), fields=('organization_id', 'task', 'channel', 'remind_at'), name='uniq_pending_task_reminder'),
        ),
        migrations.AddIndex(
            model_name='tasksource',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='tasks_task__organiz_5482d4_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksource',
            index=models.Index(fields=['created_at'], name='tasks_task__created_67a807_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksource',
            index=models.Index(fields=['organization_id', 'source_type', 'source_id'], name='tasks_task__organiz_ac2a1b_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksource',
            index=models.Index(fields=['organization_id', 'source_message'], name='tasks_task__organiz_39d64a_idx'),
        ),
        migrations.AddIndex(
            model_name='tasksource',
            index=models.Index(fields=['organization_id', 'task'], name='tasks_task__organiz_784279_idx'),
        ),
        migrations.AddConstraint(
            model_name='tasksource',
            constraint=models.UniqueConstraint(condition=models.Q(('normalized_title__gt', ''), ('source_message__isnull', False)), fields=('organization_id', 'source_message', 'normalized_title'), name='uniq_task_source_message_title'),
        ),
        migrations.AddIndex(
            model_name='taskstatushistory',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='tasks_task__organiz_b737b3_idx'),
        ),
        migrations.AddIndex(
            model_name='taskstatushistory',
            index=models.Index(fields=['created_at'], name='tasks_task__created_e1caa9_idx'),
        ),
        migrations.AddIndex(
            model_name='taskstatushistory',
            index=models.Index(fields=['organization_id', 'task', 'created_at'], name='tasks_task__organiz_716870_idx'),
        ),
    ]
