from django.urls import path

from .provider_views import (
    AIConnectionView,
    AIProviderDetailView,
    AIProvidersView,
)
from .views import (
    AIEvalResultDetailView,
    AIEvalResultsView,
    AIEvalRunView,
    AIModelConfigActivateView,
    AIModelConfigDetailView,
    AIModelConfigsView,
    AIPromptDetailView,
    AIPromptsView,
    AIPromptVersionActivateView,
    AIPromptVersionArchiveView,
    AIPromptVersionDetailView,
    AIPromptVersionsView,
    AIRunDetailView,
    AIRunMessagesView,
    AIRunRetryView,
    AIRunsView,
    AIRunToolCallsView,
    AIToolCallDetailView,
    AIToolCallsView,
    AIToolsView,
    AIUsageByDayView,
    AIUsageByModelView,
    AIUsageByPurposeView,
    AIUsageView,
    ProjectBriefView,
)

urlpatterns = [
    path("runs/", AIRunsView.as_view(), name="ai-runs"),
    path("runs/<uuid:run_id>/", AIRunDetailView.as_view(), name="ai-run-detail"),
    path("runs/<uuid:run_id>/messages/", AIRunMessagesView.as_view(), name="ai-run-messages"),
    path("runs/<uuid:run_id>/tool-calls/", AIRunToolCallsView.as_view(), name="ai-run-tool-calls"),
    path("runs/<uuid:run_id>/retry/", AIRunRetryView.as_view(), name="ai-run-retry"),
    path("prompts/", AIPromptsView.as_view(), name="ai-prompts"),
    path("prompts/<uuid:prompt_id>/", AIPromptDetailView.as_view(), name="ai-prompt-detail"),
    path(
        "prompts/<uuid:prompt_id>/versions/",
        AIPromptVersionsView.as_view(),
        name="ai-prompt-versions",
    ),
    path(
        "prompts/<uuid:prompt_id>/versions/<uuid:version_id>/",
        AIPromptVersionDetailView.as_view(),
        name="ai-prompt-version-detail",
    ),
    path(
        "prompts/<uuid:prompt_id>/versions/<uuid:version_id>/activate/",
        AIPromptVersionActivateView.as_view(),
        name="ai-prompt-version-activate",
    ),
    path(
        "prompts/<uuid:prompt_id>/versions/<uuid:version_id>/archive/",
        AIPromptVersionArchiveView.as_view(),
        name="ai-prompt-version-archive",
    ),
    path("model-configs/", AIModelConfigsView.as_view(), name="ai-model-configs"),
    path(
        "model-configs/<uuid:config_id>/",
        AIModelConfigDetailView.as_view(),
        name="ai-model-config-detail",
    ),
    path(
        "model-configs/<uuid:config_id>/activate/",
        AIModelConfigActivateView.as_view(),
        name="ai-model-config-activate",
    ),
    path("providers/", AIProvidersView.as_view(), name="ai-providers"),
    path(
        "providers/<uuid:provider_id>/",
        AIProviderDetailView.as_view(),
        name="ai-provider-detail",
    ),
    path("connection/", AIConnectionView.as_view(), name="ai-connection"),
    path("project-briefs/", ProjectBriefView.as_view(), name="ai-project-briefs"),
    path("tools/", AIToolsView.as_view(), name="ai-tools"),
    path("tool-calls/", AIToolCallsView.as_view(), name="ai-tool-calls"),
    path(
        "tool-calls/<uuid:tool_call_id>/",
        AIToolCallDetailView.as_view(),
        name="ai-tool-call-detail",
    ),
    path("usage/", AIUsageView.as_view(), name="ai-usage"),
    path("usage/by-purpose/", AIUsageByPurposeView.as_view(), name="ai-usage-by-purpose"),
    path("usage/by-model/", AIUsageByModelView.as_view(), name="ai-usage-by-model"),
    path("usage/by-day/", AIUsageByDayView.as_view(), name="ai-usage-by-day"),
    path("evals/run/", AIEvalRunView.as_view(), name="ai-evals-run"),
    path("evals/results/", AIEvalResultsView.as_view(), name="ai-eval-results"),
    path(
        "evals/results/<uuid:result_id>/",
        AIEvalResultDetailView.as_view(),
        name="ai-eval-result-detail",
    ),
]
