# Generated by Django 5.2.15 on 2026-06-11 03:29

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIBehaviorPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('default_provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('fake', 'Fake')], default='openai', max_length=32)),
                ('fallback_provider', models.CharField(blank=True, choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('fake', 'Fake')], max_length=32, null=True)),
                ('default_sales_model', models.CharField(blank=True, max_length=120)),
                ('default_support_model', models.CharField(blank=True, max_length=120)),
                ('max_context_messages', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)])),
                ('temperature_sales', models.DecimalField(decimal_places=2, default=0.4, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('temperature_support', models.DecimalField(decimal_places=2, default=0.2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('auto_reply_enabled', models.BooleanField(default=False)),
                ('human_handoff_required_for_risks', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'settings_ai_behavior_policy',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='settings_ai_organiz_b671e0_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization_id',), name='uniq_ai_policy_organization', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('owner_phone', models.CharField(blank=True, max_length=32)),
                ('default_language', models.CharField(default='es', max_length=16)),
                ('timezone', models.CharField(default='America/Argentina/Buenos_Aires', max_length=64)),
                ('business_description', models.TextField(blank=True)),
                ('services_offered', models.JSONField(blank=True, default=list)),
                ('target_clients', models.JSONField(blank=True, default=list)),
                ('brand_tone', models.CharField(blank=True, max_length=255)),
                ('calendar_link', models.URLField(blank=True, max_length=500)),
                ('website_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'settings_business_profile',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='settings_bu_organiz_189bbb_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization_id',), name='uniq_business_profile_organization', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='NotificationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notify_on_new_lead', models.BooleanField(default=True)),
                ('notify_on_human_handoff', models.BooleanField(default=True)),
                ('notify_on_failed_ai_reply', models.BooleanField(default=True)),
                ('notification_channels', models.JSONField(blank=True, default=list)),
                ('quiet_hours', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'settings_notification_policy',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='settings_no_organiz_31b7ec_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization_id',), name='uniq_notification_policy_organization', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='SalesPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('main_sales_goal', models.TextField(blank=True)),
                ('call_to_action', models.CharField(blank=True, max_length=255)),
                ('can_quote_prices', models.BooleanField(default=False)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_policy_text', models.TextField(blank=True)),
                ('must_handoff_for_price', models.BooleanField(default=True)),
                ('common_objections', models.JSONField(blank=True, default=list)),
                ('forbidden_claims', models.JSONField(blank=True, default=list)),
                ('sales_tone', models.CharField(default='professional_consultative', max_length=255)),
            ],
            options={
                'db_table': 'settings_sales_policy',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='settings_sa_organiz_379641_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization_id',), name='uniq_sales_policy_organization', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='SupportPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('support_hours', models.JSONField(blank=True, default=dict)),
                ('allowed_support_actions', models.JSONField(blank=True, default=list)),
                ('forbidden_support_actions', models.JSONField(blank=True, default=list)),
                ('urgent_keywords', models.JSONField(blank=True, default=list)),
                ('critical_ticket_rules', models.JSONField(blank=True, default=list)),
                ('data_request_policy', models.TextField(blank=True)),
                ('default_support_reply', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'settings_support_policy',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='settings_su_organiz_8b14a5_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization_id',), name='uniq_support_policy_organization', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('auto_reply_enabled', models.BooleanField(default=False)),
                ('business_hours', models.JSONField(blank=True, default=dict)),
                ('handoff_keywords', models.JSONField(blank=True, default=list)),
                ('opt_out_keywords', models.JSONField(blank=True, default=list)),
                ('allowed_outbound_templates', models.JSONField(blank=True, default=list)),
                ('media_download_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'settings_whatsapp_policy',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='settings_wh_organiz_21ce66_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization_id',), name='uniq_whatsapp_policy_organization', nulls_distinct=False)],
            },
        ),
    ]
