# Generated by Django 5.2.15 on 2026-06-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='owner_writing_style',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='signature_phrases',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
