# Generated by Django 5.2.15 on 2026-06-20 03:16

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_settings', '0002_businessprofile_owner_writing_style_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectingPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('agent_paused', models.BooleanField(default=False)),
                ('send_start_hour', models.PositiveSmallIntegerField(default=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('send_cutoff_hour', models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('org_daily_cap', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'settings_prospecting_policy',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='settings_pr_organiz_59d13a_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization_id',), name='uniq_prospecting_policy_organization', nulls_distinct=False)],
            },
        ),
    ]
