# Generated by Django 5.2.15 on 2026-06-11 03:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, max_length=1024)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('size', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'contacts_company',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='contacts_co_organiz_22affd_idx'), models.Index(fields=['created_at'], name='contacts_co_created_296db7_idx'), models.Index(fields=['organization_id', 'name'], name='contacts_co_organiz_c9831b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('display_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('unknown', 'Unknown'), ('manual', 'Manual'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('import', 'Import'), ('api', 'API'), ('system', 'System')], default='unknown', max_length=32)),
                ('type', models.CharField(choices=[('unknown', 'Unknown'), ('lead', 'Lead'), ('client', 'Client'), ('internal', 'Internal'), ('supplier', 'Supplier'), ('blocked', 'Blocked')], db_index=True, default='unknown', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked'), ('archived', 'Archived')], default='active', max_length=32)),
                ('language', models.CharField(default='es', max_length=16)),
                ('timezone', models.CharField(default='America/Argentina/Buenos_Aires', max_length=64)),
                ('avatar_url', models.URLField(blank=True, max_length=1024)),
                ('summary', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'contacts_contact',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='contacts_co_organiz_014a7b_idx'), models.Index(fields=['created_at'], name='contacts_co_created_71b3b6_idx'), models.Index(fields=['organization_id', 'display_name'], name='contacts_co_organiz_a4d87d_idx'), models.Index(fields=['organization_id', 'type', 'status'], name='contacts_co_organiz_d73d5c_idx'), models.Index(fields=['organization_id', 'updated_at'], name='contacts_co_organiz_e431ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('is_primary', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_links', to='contacts.company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_links', to='contacts.contact')),
            ],
            options={
                'db_table': 'contacts_contact_company',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='contacts_co_organiz_dc75e6_idx'), models.Index(fields=['created_at'], name='contacts_co_created_8e035e_idx'), models.Index(fields=['contact', 'is_primary'], name='contacts_co_contact_ea8e9c_idx'), models.Index(fields=['company'], name='contacts_co_company_f3555f_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization_id', 'contact', 'company'), name='uniq_contact_company_org_contact_company')],
            },
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('email', models.EmailField(max_length=254)),
                ('normalized_email', models.CharField(max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='contacts.contact')),
            ],
            options={
                'db_table': 'contacts_contact_email',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='contacts_co_organiz_f5c33a_idx'), models.Index(fields=['created_at'], name='contacts_co_created_44f3d3_idx'), models.Index(fields=['organization_id', 'normalized_email'], name='contacts_co_organiz_21c9d8_idx'), models.Index(fields=['contact', 'is_primary'], name='contacts_co_contact_fcd0ee_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization_id', 'normalized_email'), name='uniq_contact_email_org_normalized')],
            },
        ),
        migrations.CreateModel(
            name='ContactEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('event_type', models.CharField(max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='contacts.contact')),
            ],
            options={
                'db_table': 'contacts_contact_event',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='contacts_co_organiz_475fc1_idx'), models.Index(fields=['created_at'], name='contacts_co_created_a70f68_idx'), models.Index(fields=['contact', 'occurred_at'], name='contacts_co_contact_3eba50_idx'), models.Index(fields=['organization_id', 'event_type'], name='contacts_co_organiz_22b789_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('body', models.TextField()),
                ('visibility', models.CharField(choices=[('internal', 'Internal'), ('team', 'Team'), ('private', 'Private')], default='internal', max_length=16)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_notes', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='contacts.contact')),
            ],
            options={
                'db_table': 'contacts_contact_note',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='contacts_co_organiz_3d9516_idx'), models.Index(fields=['created_at'], name='contacts_co_created_015f98_idx'), models.Index(fields=['contact', 'created_at'], name='contacts_co_contact_3a76d1_idx'), models.Index(fields=['organization_id', 'visibility'], name='contacts_co_organiz_9c8a61_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('phone_e164', models.CharField(max_length=20)),
                ('country_code', models.CharField(blank=True, max_length=8)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_whatsapp', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='contacts.contact')),
            ],
            options={
                'db_table': 'contacts_contact_phone',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='contacts_co_organiz_df564f_idx'), models.Index(fields=['created_at'], name='contacts_co_created_69e365_idx'), models.Index(fields=['organization_id', 'phone_e164'], name='contacts_co_organiz_9e79f9_idx'), models.Index(fields=['contact', 'is_primary'], name='contacts_co_contact_1ba32f_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization_id', 'phone_e164'), name='uniq_contact_phone_org_e164')],
            },
        ),
        migrations.CreateModel(
            name='ContactTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=80)),
                ('color', models.CharField(blank=True, max_length=16)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='contacts.contact')),
            ],
            options={
                'db_table': 'contacts_contact_tag',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='contacts_co_organiz_e72825_idx'), models.Index(fields=['created_at'], name='contacts_co_created_219598_idx'), models.Index(fields=['organization_id', 'slug'], name='contacts_co_organiz_c4c1ca_idx'), models.Index(fields=['contact'], name='contacts_co_contact_93b224_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization_id', 'contact', 'slug'), name='uniq_contact_tag_org_contact_slug')],
            },
        ),
    ]
