# Generated by Django 5.2.15 on 2026-06-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='source',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('manual', 'Manual'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('import', 'Import'), ('api', 'API'), ('system', 'System'), ('prospecting', 'Prospecting')], default='unknown', max_length=32),
        ),
    ]
