# Generated by Django 5.2.15 on 2026-06-12 17:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('contacts', '0001_initial'),
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportKnownIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('bug', 'Bug'), ('access', 'Access'), ('billing', 'Billing'), ('feature_request', 'Feature request'), ('integration', 'Integration'), ('performance', 'Performance'), ('data_issue', 'Data issue'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved'), ('archived', 'Archived')], default='active', max_length=16)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=12)),
                ('matching_keywords', models.JSONField(blank=True, default=list)),
                ('resolution_notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'support_known_issue',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='support_kno_organiz_6d71e5_idx'), models.Index(fields=['created_at'], name='support_kno_created_cdb22d_idx'), models.Index(fields=['organization_id', 'status', 'category'], name='support_kno_organiz_191aa1_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('conversation_id', models.UUIDField(blank=True, null=True)),
                ('source_message_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('waiting_client', 'Waiting client'), ('triaged', 'Triaged'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='medium', max_length=12)),
                ('category', models.CharField(choices=[('bug', 'Bug'), ('access', 'Access'), ('billing', 'Billing'), ('feature_request', 'Feature request'), ('integration', 'Integration'), ('performance', 'Performance'), ('data_issue', 'Data issue'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('technical_summary', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='clients.client')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets', to='contacts.contact')),
            ],
            options={
                'db_table': 'support_ticket',
            },
        ),
        migrations.CreateModel(
            name='SupportResolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField()),
                ('root_cause', models.TextField(blank=True)),
                ('resolution_steps', models.TextField(blank=True)),
                ('resolved_by_id', models.UUIDField(blank=True, null=True)),
                ('resolved_by_type', models.CharField(choices=[('user', 'User'), ('ai_agent', 'AI agent'), ('system', 'System')], default='user', max_length=16)),
                ('ai_run_id', models.UUIDField(blank=True, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='support.supportticket')),
            ],
            options={
                'db_table': 'support_resolution',
            },
        ),
        migrations.CreateModel(
            name='SupportTicketAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source_message_id', models.UUIDField(blank=True, null=True)),
                ('attachment_type', models.CharField(choices=[('audio', 'Audio'), ('image', 'Image'), ('document', 'Document'), ('log', 'Log'), ('screenshot', 'Screenshot'), ('generated_asset', 'Generated asset'), ('other', 'Other')], default='other', max_length=20)),
                ('media_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_attachments', to='media.mediaasset')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.supportticket')),
            ],
            options={
                'db_table': 'support_ticket_attachment',
            },
        ),
        migrations.CreateModel(
            name='SupportTicketComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('author_type', models.CharField(choices=[('user', 'User'), ('ai_agent', 'AI agent'), ('system', 'System'), ('worker', 'Worker'), ('webhook', 'Webhook'), ('client', 'Client')], default='user', max_length=16)),
                ('author_id', models.UUIDField(blank=True, null=True)),
                ('body', models.TextField()),
                ('visibility', models.CharField(choices=[('internal', 'Internal'), ('client', 'Client')], default='internal', max_length=12)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='support.supportticket')),
            ],
            options={
                'db_table': 'support_ticket_comment',
            },
        ),
        migrations.CreateModel(
            name='SupportTicketEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status changed'), ('assigned', 'Assigned'), ('comment_added', 'Comment added'), ('attachment_added', 'Attachment added'), ('triaged', 'Triaged'), ('priority_changed', 'Priority changed'), ('resolved', 'Resolved'), ('reopened', 'Reopened'), ('closed', 'Closed'), ('ai_summary_generated', 'AI summary generated'), ('owner_notified', 'Owner notified')], max_length=32)),
                ('actor_type', models.CharField(choices=[('user', 'User'), ('ai_agent', 'AI agent'), ('system', 'System'), ('worker', 'Worker'), ('webhook', 'Webhook'), ('client', 'Client')], default='system', max_length=16)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='support.supportticket')),
            ],
            options={
                'db_table': 'support_ticket_event',
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='support_tic_organiz_7a943f_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['created_at'], name='support_tic_created_438cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['organization_id', 'status'], name='support_tic_organiz_153649_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['organization_id', 'priority'], name='support_tic_organiz_4216af_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['organization_id', 'category'], name='support_tic_organiz_991a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['organization_id', 'client'], name='support_tic_organiz_94d0b1_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['organization_id', 'contact'], name='support_tic_organiz_07e6d9_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['organization_id', 'assigned_user'], name='support_tic_organiz_304de8_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['organization_id', 'due_at'], name='support_tic_organiz_c22157_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['source_message_id'], name='support_tic_source__c05e23_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportticket',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('source_message_id__isnull', False)), fields=('organization_id', 'source_message_id'), name='uniq_ticket_per_source_message'),
        ),
        migrations.AddIndex(
            model_name='supportresolution',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='support_res_organiz_916042_idx'),
        ),
        migrations.AddIndex(
            model_name='supportresolution',
            index=models.Index(fields=['created_at'], name='support_res_created_113bc8_idx'),
        ),
        migrations.AddIndex(
            model_name='supportresolution',
            index=models.Index(fields=['ticket', 'created_at'], name='support_res_ticket__98fc96_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketattachment',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='support_tic_organiz_0837b8_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketattachment',
            index=models.Index(fields=['created_at'], name='support_tic_created_2caaa6_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketattachment',
            index=models.Index(fields=['ticket'], name='support_tic_ticket__81dbb1_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketattachment',
            index=models.Index(fields=['organization_id', 'attachment_type'], name='support_tic_organiz_a0200b_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketcomment',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='support_tic_organiz_87d1f7_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketcomment',
            index=models.Index(fields=['created_at'], name='support_tic_created_ee19e8_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketcomment',
            index=models.Index(fields=['ticket', 'created_at'], name='support_tic_ticket__94e637_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketcomment',
            index=models.Index(fields=['organization_id', 'visibility'], name='support_tic_organiz_f1e3a9_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketevent',
            index=models.Index(fields=['organization_id', 'deleted_at'], name='support_tic_organiz_683f8b_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticketevent',
            index=models.Index(fields=['organization_id', 'ticket', 'created_at'], name='support_tic_organiz_358e69_idx'),
        ),
    ]
