# Generated by Django 5.2.15 on 2026-06-16 17:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectingCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=255)),
                ('vertical', models.CharField(blank=True, max_length=120)),
                ('query', models.CharField(max_length=255)),
                ('location_hint', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activa'), ('paused', 'Pausada'), ('completed', 'Completada'), ('archived', 'Archivada')], default='draft', max_length=16)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='whatsapp', max_length=16)),
                ('target_profile', models.TextField(blank=True)),
                ('min_fit_score', models.PositiveSmallIntegerField(default=60)),
                ('auto_contact', models.BooleanField(default=False)),
                ('daily_cap', models.PositiveSmallIntegerField(default=20)),
                ('discovered_count', models.PositiveIntegerField(default=0)),
                ('qualified_count', models.PositiveIntegerField(default=0)),
                ('contacted_count', models.PositiveIntegerField(default=0)),
                ('interested_count', models.PositiveIntegerField(default=0)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prospecting_campaign',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='prospecting_organiz_77216e_idx'), models.Index(fields=['created_at'], name='prospecting_created_192c60_idx'), models.Index(fields=['organization_id', 'status'], name='prospecting_organiz_e9bf21_idx')],
            },
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('place_id', models.CharField(blank=True, max_length=255)),
                ('business_name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('website', models.CharField(blank=True, max_length=500)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('photos_count', models.PositiveIntegerField(default=0)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('discovered', 'Descubierto'), ('qualified', 'Calificado'), ('approved', 'Aprobado'), ('contacted', 'Contactado'), ('replied', 'Respondió'), ('interested', 'Interesado'), ('not_interested', 'No interesado'), ('disqualified', 'Descalificado'), ('do_not_contact', 'No contactar'), ('failed', 'Falló')], default='discovered', max_length=20)),
                ('fit_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('signals', models.JSONField(blank=True, default=list)),
                ('reasoning', models.TextField(blank=True)),
                ('recommended_angle', models.TextField(blank=True)),
                ('contact_id', models.UUIDField(blank=True, null=True)),
                ('conversation_id', models.UUIDField(blank=True, null=True)),
                ('lead_id', models.UUIDField(blank=True, null=True)),
                ('ai_run_id', models.UUIDField(blank=True, null=True)),
                ('qualified_at', models.DateTimeField(blank=True, null=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospects', to='prospecting.prospectingcampaign')),
            ],
            options={
                'db_table': 'prospecting_prospect',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='prospecting_organiz_c9bdc9_idx'), models.Index(fields=['created_at'], name='prospecting_created_bc657e_idx'), models.Index(fields=['organization_id', 'campaign'], name='prospecting_organiz_eb7092_idx'), models.Index(fields=['organization_id', 'status'], name='prospecting_organiz_c77946_idx'), models.Index(fields=['campaign', 'status'], name='prospecting_campaig_0cb595_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('place_id', ''), _negated=True)), fields=('organization_id', 'campaign', 'place_id'), name='uniq_prospect_campaign_place')],
            },
        ),
    ]
