# Generated by Django 5.2.15 on 2026-06-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='enriched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='enrichment',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='prospect',
            name='has_online_booking',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='latest_review_age_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='website_platform',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='prospect',
            name='website_reachable',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
