# Generated by Django 5.2.15 on 2026-06-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0002_prospect_enriched_at_prospect_enrichment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='pagespeed_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
