# Generated by Django 5.2.15 on 2026-06-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0003_prospect_pagespeed_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='external_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='prospect',
            name='external_source',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='prospect',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='prospect',
            name='owner_email_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='prospect',
            name='owner_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='prospectingcampaign',
            name='source',
            field=models.CharField(choices=[('google_places', 'Google Places'), ('apollo', 'Apollo')], default='google_places', max_length=32),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['organization_id', 'external_source', 'external_id'], name='prospecting_organiz_f68f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectingcampaign',
            index=models.Index(fields=['organization_id', 'source'], name='prospecting_organiz_352415_idx'),
        ),
        migrations.AddConstraint(
            model_name='prospect',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('external_source', ''), _negated=True), models.Q(('external_id', ''), _negated=True)), fields=('organization_id', 'campaign', 'external_source', 'external_id'), name='uniq_prospect_campaign_external'),
        ),
    ]
