# Generated by Django 5.2.15 on 2026-06-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0004_prospect_external_id_prospect_external_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='follow_up_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prospect',
            name='last_touch_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='next_followup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='touch_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prospectingcampaign',
            name='auto_followup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prospectingcampaign',
            name='auto_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prospectingcampaign',
            name='max_touches',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['campaign', 'next_followup_at'], name='prospecting_campaig_d3e511_idx'),
        ),
    ]
