# Generated by Django 5.2.15 on 2026-06-20 03:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospecting', '0005_prospect_follow_up_count_prospect_last_touch_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectingcampaign',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email')], default='whatsapp', max_length=16),
        ),
        migrations.CreateModel(
            name='ProspectEmailMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='queued', max_length=24)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('bounced_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='prospecting.prospectingcampaign')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='prospecting.prospect')),
            ],
            options={
                'db_table': 'prospecting_email_message',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='prospecting_organiz_0385f4_idx'), models.Index(fields=['campaign', 'status'], name='prospecting_campaig_d312f9_idx'), models.Index(fields=['status', 'available_at'], name='prospecting_status_6a4dbd_idx'), models.Index(fields=['organization_id', 'to_email'], name='prospecting_organiz_18dd2c_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization_id', 'idempotency_key'), name='uniq_prospect_email_idempotency', nulls_distinct=False)],
            },
        ),
    ]
