# Generated by Django 5.2.15 on 2026-06-13 20:25

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandKit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('tax_id', models.CharField(blank=True, max_length=64)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('primary_color', models.CharField(default='#7C6CFF', max_length=9)),
                ('accent_color', models.CharField(default='#22C55E', max_length=9)),
                ('text_color', models.CharField(default='#16161D', max_length=9)),
                ('currency', models.CharField(default='ARS', max_length=8)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('21'), max_digits=5)),
                ('default_terms', models.TextField(blank=True)),
                ('footer_note', models.CharField(blank=True, max_length=255)),
                ('logo_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset')),
            ],
            options={
                'db_table': 'documents_brand_kit',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='documents_b_organiz_b4669d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization_id',), name='uniq_brand_kit_per_org')],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('doc_type', models.CharField(choices=[('proposal', 'Propuesta'), ('quote', 'Presupuesto'), ('invoice', 'Factura'), ('report', 'Informe'), ('deck', 'Presentación')], max_length=32)),
                ('doc_format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel'), ('pptx', 'PowerPoint')], max_length=8)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('ready', 'Listo'), ('sent', 'Enviado'), ('failed', 'Falló')], default='ready', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('client_id', models.UUIDField(blank=True, null=True)),
                ('lead_id', models.UUIDField(blank=True, null=True)),
                ('conversation_id', models.UUIDField(blank=True, null=True)),
                ('contact_id', models.UUIDField(blank=True, null=True)),
                ('ai_run_id', models.UUIDField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('media_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediaasset')),
            ],
            options={
                'db_table': 'documents_generated_document',
                'indexes': [models.Index(fields=['organization_id', 'deleted_at'], name='documents_g_organiz_74cb03_idx'), models.Index(fields=['created_at'], name='documents_g_created_8ada8c_idx'), models.Index(fields=['organization_id', 'status'], name='documents_g_organiz_c729a8_idx'), models.Index(fields=['organization_id', 'doc_type'], name='documents_g_organiz_72208b_idx')],
            },
        ),
    ]
